.h2 Who are we?

.p This is an interesting question as there is a heterogenous global community fascinated by the idea of open mobile phones and open hardware in general.
.p Many of "us" care a lot about private communcation -  in case you are working for some intelligence agency better bookmark this page.
.p Check out the [community portal->http://wiki.openmoko.org/wiki/Openmoko:Community_Portal] in the wiki. It's a bit outdated but a great resource.

.p We long for
.li completely open phone (100% software, 99% hardware)
.li privacy enhancements
.li fair labour conditions for production and assembly
.li clean resources (beyond war areas / human rights violations)
.li open process - everybody can [join->Mailinglist] in and [contribute->#contribute]

.a our homepage: http://openphoenux.org
.a Facts and Reasons: http://projects.goldelico.com/p/gta04-main/page/FactsAndReasons
.p For more information see _Facts and Reasons_ and the [Wikipedia article->https://en.wikipedia.org/wiki/OpenMoko] for the complete picture.

.img openphoenux_logo.png

.h2 And why the name 'phoenux'?

.p Openmoko declared the open mobile communication project dead but phoenux will arise from the ashes to the heaven of Linux ..