.p Most important for the open phone community are [donations->http://shop.goldelico.com/wiki.php?page=Openmoko:Community&referer=] to continue the production of our current revision.
.p If you like this project and want to contribute, great! Whatever you are able to do please do. We don't want to limit your creativity :)
.p We are constantly looking for support to research about the labour conditions about our supplyers. Please also subscribe to <a href="http://lists.openphoenux.org/mailman/listinfo/community" target="_blank">our list</a> and say "Hello!" :)
.p Besides this we would love to receive help with the following
.li Compress this page and available information to a leaflet and spread it (very important)
.li vote for improvements an this and our [sister page->http://slyon.de/gta04/index.old.php]
.li Tell all your friends about this project and other [open hardware->https://we.riseup.net/opensourcehardware] initiatives (for example this [open geiger counter->http://www.indiegogo.com/project/preview/880f9dba])
.p To improve this page check out the code at [github->https://github.com/kradan/openphoenux.org].
