.note To upgrade your [GTA02->http://wiki.openmoko.org/wiki/GTA02], [click here->https://shop.goldelico.com/wiki.php?page=GTA04] or see the [GTA04 main page->http://projects.goldelico.com/p/gta04-main/].

.h2 Applause for the OpenPhoenux, please!

.p The <b>GTA04</b>, codename 'Phoenux', is the successor of 'Freerunner' ([PDF->pdf/DataSheetOpenmokoFreerunner.pdf]), the first open mobile phone produced by [OpenMoko->https://en.wikipedia.org/wiki/OpenMoko], which dropped development in 2009. (See [history->http://blog.slyon.de/2012/12/21/openmoko-openphoenux-gta04-jumps-off/] for details.)

.gallery> beagleboard.png 2010_board_parts_1.png 2010_board_parts_2.png 2011_GTA04A2.png keyboard_prototype.png

.p [GoldenDelicious->http://goldelico.com/Hardware.html] from Munich jumped in and decided to give the [community->http://projects.goldelico.com/p/gta04-main/page/CaseDesign/] new hope by equipping the [beagleboard->https://secure.wikimedia.org/wikipedia/de/wiki/Beagle_Board] with all necessary [features->#hardware] for a modern phone with

* Full [Linux support->http://projects.goldelico.com/p/gta04-main/page/Software]
* Open [schematics->pdf/GTA04.sch.pdf]
* Open layout
* [Expansion connectors->http://shop.goldelico.com/wiki.php?page=GTA04:RS232&referer=]
* Lots of [documentation->http://projects.goldelico.com/p/gta04-main/page/Manual/]
* [many components->http://shop.goldelico.com/wiki.php?page=Openmoko:Community&referer=]

.p What began as an upgrade board for the [GTA02->http://wiki.openmoko.org/wiki/GTA02] became an independent phone when new [cases->#case] were [developed->http://projects.goldelico.com/p/gta04-main/page/CaseDesign/]. 

.p And there are more options:
* Take the schematics and [do what you want->#license]!
* Equip it with a [camera->http://shop.goldelico.com/wiki.php?page=GTA04:Camera&referer=]
* Create a new [case design->http://projects.goldelico.com/p/gta04-main/page/CaseDesign/]
* Test and develop the [hardware keyboard->https://shop.goldelico.com/wiki.php?page=GTA04%3AKeyboard&referer=keyboard]
* Have a look at the [contribution->#join] page.
* Be [generous->#price].
* Be [creative->#contribute].
