.a mailing list: http://lists.openphoenux.org/mailman/listinfo/community
.a news: http://projects.goldelico.com/p/gta04-main/page/News
.a web: http://openphoenux.org
.a rss: http://blog.slyon.de/feed/
<div id="nav" class="wide bar">
.p#links  _rss_ - _news_ - _mailing list_ - _web_
.p#date <!-- hhmts start -->Last modified: $date <!-- hhmts end -->
 <address>openphoenux.org</address>
</div>

<div id="top" class="wide">
<div id="banner">
 <div class="left">
  <h1>Open Phoenux <span>[o.pen fi.nuks]</span></h1>
  <h2>Free your phone by running Linux!</h2>
 </div>
 <a href="."><img src="images/openphoenux_logo.png" width="100" alt="openphoenux.org" /></a>
 <div class="right">
  <p>Are you ready for the next generation mobile phone?</p>
  <p>No backdoors. No locks.<br/>Full control through open hard- and software.</p>
 </div>
</div>
</div>
