.img GTA02_Letux2804.jpg GTA02 Letux 2804 -> https://shop.goldelico.com/wiki.php?page=GTA04
.img GTA04_wooden_case3.png Radek's Wooden case -> #case
.img gta04_white.png gta04 white case
.img Letux3704.png Letux 3704 PDA -> http://shop.goldelico.com/wiki.php?page=Letux%203704&referer=
.img Letux7004_tablet.png Letux 7004 Tablet -> http://shop.goldelico.com/wiki.php?page=Letux%207004&referer=
.img Letux7004_prototype.png Letux 7004 Tablet -> http://shop.goldelico.com/wiki.php?page=Letux%207004&referer=
.img neo900.jpg Neo900 -> http://neo900.org/
