<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-15">
<title>openphoenux.org</title>
<link rel="icon" href="images/phoenix.ico" type="image/x-icon" />
<link rel="shortcut icon" href="images/phoenix.ico" type="image/x-icon" />
<style type="text/css">
<!-- #include:css -->
</style>
<link rel="stylesheet" type="text/css" href="main.css" media="screen">
<link rel="stylesheet" type="text/css" href="print.css" media="print">
</head>
<body>

<!-- include:header -->

<div id="top" class="menu">
 <div class="content">
<!-- include:gta04 -->
 </div>
<!-- top:hardware Hardware -->
<!-- top:case Case -->
<!-- top:production Production -->
<!-- top:os Software -->
<!-- top:price Price -->
<!-- top:order Order -->
<!-- top:contribute Contribute -->
</div><!-- /top -->

<div id="left" class="menu">
<!-- left:why Why? -->
<!-- left:status News -->
<!-- left:faq FAQ -->
<!-- left:about About -->
 <div id="images">
<!-- include:images -->
 </div>
</div><!-- /left -->

<!-- design structure
........ logo ..........
| OpenPhoenux  | Blog  |
| Status Price |       |
| ------ images ------ |
| Problems    | Pros   |
| Production  | Price  |
| Case        | OS     |
| [Social] Links       |
........................
-->

 </body>
</html>
