.h2 Awesome. Get me a GTA04!

.gallery> gta04_white.png case_PCB_result.png GTA04_wooden_case3.png GTA04_wooden_case2.png case_transparent.png Letux3704.png Letux7004_tablet.png Letux7004_prototype.png
.img= gta04_features.png Features -> #hardware
.img= GTA04_board.jpeg 

.p There currently is no stock since we are waiting for orders. Please use the [wishlist form->https://shop.goldelico.com/wiki.php?page=Wishlist] at the [delicious webshop->https://shop.goldelico.com/wiki.php?page=GTA04] to indicate your interest.

.p To stay informed about the [price->#price] or to discuss the latest announcements we have a _mailing list_.

.h2 I want one. Now!

.img< GTA02_Letux2804.jpg
.gallery> GTA04_parts.JPG case_white_parts.png case_white_assembled.png Letux3704_inside.png Letux7004_board.png keyboard_prototype.png 
.img> GTA04A4_group_tour.jpg GTA04 shipment of the first group tour -> http://blog.slyon.de/2012/11/02/gta04-production-is-processing/comment-page-1

.p Ok, for developers there are some last units of the [GTA04A4->http://projects.goldelico.com/p/gta04-main/page/Versions]. They are not perfect, please ask [goldendelicious->mailto:sales@goldelico.com?subject=GTA04A4 order list] for a detailed list.

.p We offer three different product options:
* GTA04 motherboard for DIY upgrades.
* Letux 2804: preinstalled in a refurbished Openmoko GTA02 case.
* GTA04 Custom: contact us for a customized variant.

.note This is not a complete phone. You need to get a new or used [Neo 1973->https://shop.goldelico.com/wiki.php?page=1973&referer=] or [Neo Freerunner->https://shop.goldelico.com/wiki.php?page=Neo%20Freerunner&referer=] unless you purchase one of the rare complete [Letux 2804->https://shop.goldelico.com/wiki.php?page=GTA04%20Complete] units. Or you take a [Case Kit->https://shop.goldelico.com/wiki.php?page=GTA04%3ACase%20Kit&referer=] plus a 3D printed or 3D cut [case->#case].
.img< gta02-upgrade.gif

.p Key features are:
* ARM Cortex A8 processor with 1000 MHz and 512 MB RAM
* UMTS 3.75G (14 MBit/s max.)
* Integrated sensors (Barometer, Gyroscope, Accelerometer, Compass)
* optional: Camera
* USB OTG 2.0
* fits into existing Neo Freerunner case

.img= case_3Dprint.png 3D printing process -> #case
