<pre>
* OS
** 38 http://qtmoko.sf.net
** 39 SHR http://shr-project.org
** 40 Replicant http://replicant.us
** 41 Debian/LXDE http://projects.goldelico.com/p/gta04-rootfs
* 43 We could do a lot of things, if there were more support by
  interested people, e.g.: •build many more GTA04A5 boards
** build new complete devices with 3D printed cases
** build a lot of Letux 7004 tablets
** protoype a Cortex A15 variant with bigger display and LTE
** work on a hardware keyboard
* 44 
** Due to the open bootloader, open drivers
and open documentation it is possible to
port any OS to the GTA04 platform.
** Are YOU interested to port e.g. WebOS,
FirefoxOS, UbuntuPhone, SailfishOS, $
{your_favourite}OS to the most open
hardware platform available?
</pre>

Have a look at the OpenPhoenux Software Index for details:
http://www.openphoenux.org/swi/index.php?