.h2 We need your money!

.p Yes, we don't like to say, but the lights are red until we receive your support.
.p Society breaks apart in people who want to use things and others who want to personalize them. Let us know, what you want and we will find a way!
.p Diversity is great but think of the price. To minimize costs we need to raise the numbers as much as possible, to comply the needs of affordable community hardware.

.img= cost_problem.png

.p Alas our price of above 500 &euro; is still high due to the small batch size because there are not enough orders to start.
.p The next revision with 200 units could be produced within ca. 8-10 months, but we need 120.000 &euro; first. Have a look at the graph below:

.img= price_diagram.png

.h2 Is there no solution?
.p Our current strategy is twofold. While we try to raise funds we [collect your orders->#order] within a preferred price range. With [regular updates->#news] we inform the community about the current calculated price and everybody can decide to jump in when we reach an acceptable threshold.
.p Think of it as a train waiting for green lights as soon as enough passengers got in.
