.h2 News &amp; Updates

.p GTA04A5 is ready for production since summer 2012. There are few pieces left to be assembled in different cases (see pictures on the left).
.p The current mainboard revision is ready to go to production as soon as enough orders drop in.  To enter next step of production we need at least 300 orders, best would be 100.000. Have a look at the [price page->#price] for details.
.p We opened the [preorder->#order] phase and send monthly announcements to all members of our wishlist. For detailed updates you can subcribe the _mailing list_.

<cite>
"If 200 people agree to put 599 EUR on the table we could start production tomorrow (well, we need 6-8 weeks to get the components) and 200 GTA04 boards would be available in November.
We could also order 200 3D-printed cases, earpieces etc. to make complete phones. One issue is that we have just ~70 display modules, and they are out of production for a long time. But there may be some remaining stock in Asia, so it appears to be a solvable problem.
Doing a redesign for a different display, different case (N900) is also possible, but takes more time (estimate 4-6 months).
But it also needs 200 * 599 EUR on the table. Not to start design or production (that has become my hobby), but to buy components."
</cite>
([Dr. H. Nikolaus Schaller->http://lists.openmoko.org/pipermail/community/2013-August/068816.html], August 23th 2013)

.p Major improvements of [this revision->#hardare]:
.li added DIY antenna
.li 3D printed case for daily use
.li make it an independ device (without the need to disassemble a GTA02)
.li Small modifications to replace obsolete components or improve production process
