<h2>What the inventors of PC and WWW did want</h2>
.note computation, storage and communication is personal
.note WWW connects decentralized servers and clients to share information
.note everyone controls his/her data published to the net

<h2 class="question">Phoenux stands for</h2>
.note Open Phone running Linux
.note participation by everyone
.note makes the technical system transparent, not the user
.note allows to inspect what the system is doing
.note open schematics and good documentation
.note extensible hard- and software
.note fights planned obsolescence through open hard- and software
.note long-term support (e.g. software upgrades for an 2007 Neo 1973)
.note Do It Yourself, eg.<br/>community created cases<br/>(wooden, 3D printed, aluminium)
.note can be repaired using standard parts
.note no central, intransparent, stock
.note hardware production near to users (Europe) under fair labour conditions
.note independent from the "modern mainframe" and back to the networked, decentralized web
.note everyone controls his/her data published to the net
.note you play client and server roles and keep control over your participation

<h2 class="question">Problems with closed phones</h2>
<h3>Why Android and iOS are not open enough.</h3>
.note They don't care about your privacy.
.note Try to secure your phone and data.
.note Try to understand why your device fails in a specific situation.
.note Try to get an upgrade for your 2 years old Android device.
.note not every bit and piece is open and extensible or even long-living
.note Try to provide your own home screen to iOS. Even Facebook Home failed.
.note Try to connect a hardware keyboard. If you are lucky you have an USB host port. But do you have the driver?

<h3 class="question">You know more? [Tell us->http://lists.openphoenux.org/mailman/listinfo/community] your story!</h3>